{% set data = load_setup_py_data() %}
package:
  name: simple_slurm
  version: {{ data['version'] }}
dependencies:
  - anaconda-client
  - conda-build
source:
  path: ..
build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
requirements:
  build:
    - python
    - setuptools
  run:
    - python
test:
  imports:
    - simple_slurm
about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
