name: Publish to Conda

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Install dependencies
        run: |
          conda install conda-build
          conda create -n test-env python=3.8 simple_slurm
      - name: Run tests
        run: |
          conda init
          conda activate test-env
          python -m unittest discover -s tests
      - name: Publish to Conda
        uses: fcakyon/conda-publish-action@master
        with:
          subdir: 'conda'
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'win osx linux'
