name: Run Tests Inside SLURM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "8888:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SLURM
        uses: koesterlab/setup-slurm-action@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Copy files to SLURM node
        run: |
          mkdir -p /slurm_workspace
          rsync -av --progress . /slurm_workspace/
          ls -lah /slurm_workspace  # Debugging step to check file transfer

      - name: Run tests inside SLURM
        run: |
          cd /slurm_workspace
          sbatch --wrap="python -m unittest -v"
